version: 2

sources:
  - name: BUSES
    schema: BRONZE
    tables:
      - name: BRONZE_DELAYS

      - name: BRONZE_STOPS

      - name: BRONZE_POSITIONS

      - name: BRONZE_TRIPS

      - name: BRONZE_VEHICLES

      - name: BRONZE_ROUTES
